version: 0.1

phases:
  install:
    runtime-versions:
      nodejs:7.0.0
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Bryce_Frazier_Resume.pdf
    - styles/*
    - images/*
