version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    comands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack-dev
artifacts:
  files:
    - index.html
    - favicon.ico
    - Bryce_Frazier_Resume.pdf
    - styles/*
    - images/*
    - dist/bundle.js
